# Generated by Django 4.0.4 on 2022-04-13 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncdcapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_center', models.CharField(max_length=500)),
                ('doctor_name', models.CharField(max_length=500)),
                ('ref_no', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('blood', models.CharField(blank=True, max_length=10)),
                ('cough', models.BooleanField(default=False)),
                ('fever', models.BooleanField(default=False)),
                ('measles', models.BooleanField(default=False)),
                ('rashes', models.BooleanField(default=False)),
                ('red_watery_eye', models.BooleanField(default=False)),
                ('runny_nose', models.BooleanField(default=False)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncdcapi.state_distribution')),
            ],
        ),
    ]
