# Generated by Django 4.0.4 on 2022-04-13 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncdcapi', '0002_patient_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_record',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ncdcapi.state_distribution'),
        ),
    ]
