# Generated by Django 4.0.4 on 2022-04-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncdcapi', '0003_alter_patient_record_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='lga_distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_infected', models.IntegerField()),
                ('lga_name', models.CharField(max_length=100)),
                ('Latitude_value', models.CharField(max_length=200)),
                ('Latitude_alias', models.CharField(max_length=200)),
                ('Longitude_value', models.CharField(max_length=200)),
                ('Longitude_alias', models.CharField(max_length=200)),
            ],
        ),
    ]
